AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ConvertAllToCSV:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 3008
      Timeout: 900
      Role: 'arn:aws:iam::917684643571:role/service-role/S3ReadAndWrite'
